const HEADER = [
  "// Generated by meowter — DO NOT EDIT.",
  "// Re-run `vite` (with the meowterRoutes plugin) or `meowter-routes generate`",
  "// to refresh after adding or renaming a `<meow-route>`.",
].join("\n");

/**
 * Render a `.d.ts` body that augments the `meowter` module's
 * `RouteRegistry` interface with the given paths as keys.
 */
export function emitRouteRegistryDts(paths: readonly string[]): string {
  const sorted = Array.from(paths).sort(comparePaths);
  const entries = sorted.map((p) => `    ${JSON.stringify(p)}: never;`).join("\n");

  return [
    HEADER,
    "",
    'declare module "meowter" {',
    "  interface RouteRegistry {",
    entries,
    "  }",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

function comparePaths(a: string, b: string): number {
  if (a === "*") return 1;
  if (b === "*") return -1;
  return a.localeCompare(b);
}
